"""Convert a contracts CSV export into backend/data_static/nfl_contracts.json.

The salary board reads contract money from a local file because no free live
feed exists. This script turns a Spotrac / OverTheCap style export into that
file so refreshing the money is one command rather than hand-editing JSON.

Usage:
    python backend/scripts/import_nfl_contracts.py contracts.csv
    python backend/scripts/import_nfl_contracts.py contracts.csv --source "Spotrac 2026-08-14"
    python backend/scripts/import_nfl_contracts.py contracts.csv --out backend/data_raw/nfl_contracts.json

Expected columns (case-insensitive, extras ignored, order irrelevant):
    player / player_name      required
    team                      optional
    position / pos            optional
    apy / avg / average       required — accepts 45000000, "45,000,000" or "$45M"
    total / total_value       optional
    guaranteed / gtd          optional
    years                     optional
    signed / year_signed      optional

Rows written by this script are marked ``estimated: false`` — they came from an
export rather than from memory. Anything hand-entered should keep the flag set
so the board can label it.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from app.collectors.nfl_contracts import to_money  # noqa: E402  (path bootstrap above)


COLUMN_ALIASES = {
    "player_name": ("player_name", "player", "name"),
    "team": ("team", "tm", "club"),
    "position": ("position", "pos"),
    "apy": ("apy", "avg", "average", "average_salary", "per_year", "aav"),
    "total_value": ("total_value", "total", "value", "contract_value"),
    "guaranteed": ("guaranteed", "gtd", "guarantees", "total_guaranteed"),
    "years": ("years", "yrs", "length"),
    "signed": ("signed", "year_signed", "start_year"),
}


def normalize_header(name: str) -> str:
    return "".join(character for character in str(name or "").lower() if character.isalnum() or character == "_")


def pick(row: dict[str, str], field: str) -> str | None:
    for alias in COLUMN_ALIASES[field]:
        if alias in row and str(row[alias]).strip():
            return str(row[alias]).strip()
    return None


def parse_int(value: str | None) -> int | None:
    if value is None:
        return None
    try:
        return int(float(value))
    except ValueError:
        return None


def convert(csv_path: Path) -> list[dict]:
    players: list[dict] = []
    skipped = 0

    with csv_path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        for raw_row in reader:
            row = {normalize_header(key): value for key, value in raw_row.items() if key}
            name = pick(row, "player_name")
            apy = to_money(pick(row, "apy"))
            if not name or apy is None:
                skipped += 1
                continue
            entry = {
                "player_name": name,
                "team": (pick(row, "team") or "").upper(),
                "position": (pick(row, "position") or "").upper(),
                "apy": int(apy),
                "estimated": False,
            }
            for field in ("total_value", "guaranteed"):
                money = to_money(pick(row, field))
                if money is not None:
                    entry[field] = int(money)
            for field in ("years", "signed"):
                number = parse_int(pick(row, field))
                if number is not None:
                    entry[field] = number
            players.append(entry)

    if skipped:
        print(f"[import_nfl_contracts] skipped {skipped} row(s) with no player name or no APY", file=sys.stderr)
    return players


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("csv_path", type=Path, help="CSV export to convert")
    parser.add_argument("--out", type=Path, default=PROJECT_ROOT / "data_static" / "nfl_contracts.json")
    parser.add_argument("--source", default=None, help="Provenance string stored in meta.source")
    parser.add_argument("--as-of", default=None, help="Recorded in meta.as_of, e.g. 2026-08")
    args = parser.parse_args()

    if not args.csv_path.exists():
        parser.error(f"{args.csv_path} does not exist")

    players = convert(args.csv_path)
    if not players:
        parser.error("no usable rows found — check the column names against COLUMN_ALIASES")

    payload = {
        "meta": {
            "source": args.source or f"import from {args.csv_path.name}",
            "as_of": args.as_of or "",
            "unit": "USD",
            "notes": "Generated by backend/scripts/import_nfl_contracts.py",
        },
        "players": sorted(players, key=lambda row: row["apy"], reverse=True),
    }

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"[import_nfl_contracts] wrote {len(players)} contracts to {args.out}")


if __name__ == "__main__":
    main()
